# Generated by Django 5.2.5 on 2025-09-12 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_carrinho_categoria_endereco_usuario_pedido_produto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='produtos/'),
        ),
    ]
