# Generated by Django 5.2.7 on 2025-10-24 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_image_produto_image1_remove_usuario_genero_and_more'),
        ('uploader', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='image3',
        ),
        migrations.AddField(
            model_name='produto',
            name='capa',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='uploader.image'),
        ),
    ]
