# Generated by Django 5.2.7 on 2025-10-24 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_produto_image1_remove_produto_image2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='capa',
            new_name='image',
        ),
    ]
