# Generated by Django 5.2.7 on 2025-10-24 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rename_capa_produto_image'),
        ('uploader', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='image2',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='uploader.image'),
        ),
    ]
