# Generated by Django 5.2.7 on 2025-10-30 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_produto_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='image',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='image2',
        ),
        migrations.AddField(
            model_name='produto',
            name='imagen2',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
