# Generated by Django 5.2.7 on 2025-10-30 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_produto_image_remove_produto_image2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='imagen2',
        ),
        migrations.AddField(
            model_name='produto',
            name='image1',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produto',
            name='imagen',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
