# Generated by Django 5.2.7 on 2025-10-30 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_produto_imagen_produto_imagen2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='imagen2',
        ),
        migrations.AddField(
            model_name='produto',
            name='image2',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
