# Generated by Django 5.2.7 on 2025-10-31 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_produto_imagen2_produto_image2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='passage_id',
        ),
    ]
